refine

diff --git a/bin/cat b/bin/cat
--- a/bin/cat
+++ b/bin/cat
@@ -10,7 +10,7 @@ case "$#" in
     print;;
   *)
     for i in "$@"; do
-      print < "$i"
+      [ -e "$i" ] && { print < "$i"; } || { echo "$i is missing or not a file..."; }
     done
   ;;
 esac
diff --git a/ex/cat b/ex/cat
--- a/ex/cat
+++ b/ex/cat
@@ -32,7 +32,7 @@ acase() {
       print;;
     *)
       for i in "$@"; do
-        print < "$i"
+        [ -f "$i" ] && { print < "$i"; } || { echo "$i is missing or not a file..."; }
       done
     ;;
   esac
