switch tr to case system; broken for escapes currently

diff --git a/bin/tr b/bin/tr
--- a/bin/tr
+++ b/bin/tr
@@ -1,44 +1,36 @@
 #!/bin/sh
 # shellcheck disable=SC2015,SC2059,SC2048
-c=$(while IFS=""; read -r p || [ -n "$p" ]; do
+IFS=""
+operand(){
+  printf '%s: missing operand' "${0##*/}"
+  [ ! "$2" -a "$1" ] && { printf " after '%s'\n" "$1"
+    printf 'Two strings must be given when translating.'
+  }
+  echo; exit 1
+} # handle missing args
+in=$(while IFS=""; read -r p || [ -n "$p" ]; do
   printf '%s\n' "$p"
-done <&0) # allow trailing escapes check
-r="$1"; d="$2"; [ ! "${r##\\*}" ] && {
-  unset IFS; eval << EOF
-IFS=$\'${r}'
-EOF
-:
-} || { IFS="${r}"; } # handle escapes
-set -- "$c" # turn contents of stdin into arg list
-for i in $*; do # $* is intended
-  [ ! "$e" ] && { e="$i";:; } || { e="$e$d$i";:; }
-done
+done <&0)
 
-# There was a bug here
-# trailing escapes seem to be trimmed
-# ie:
-# '1\t2\t' becomes '1\t2'
-# upon print OR read if IFS is not ""/NULL
-# when either of these take place
-#
-# the only fix I could find for this was to check if stdin ended with $IFS
-# and if it does check if $e does NOT end with $d
-# 
-# I've created a imp of this using case as follows
-# inorder for this to work I had to switch back to using $() over working line by line
+# IFS=""
+# set -- "$in"
+# for i in $*; do # $* is intended
+#   [ ! "$out" ] && { out="$i";:;} || { out="$out$d$i";}
+# done
+## this system is REQUIRED for escape replacement, but is unstable
 
-case "$c" in
-  *${IFS})
-    case "$e" in
-      *${d}) ;;
-      *) e="$e$d"
+[ ! "$1" -o ! "$2" ] && { operand "$@" ;}
+while [ -n "$in" ]; do
+    next=${in#?}
+    case "${in%$next}" in
+      "${1}")
+        printf '%s' "${2}"
+      ;;
+      *)
+        printf '%s' "${in%$next}"
     esac
-esac
+    in="$next"
+done
+# this always works but cannot match escapes
 
-printf '%s\n' "$e"
-
-# "real" tr does not output a trailing newline
-# if no trailing newline was given, but do to $() removing trailing newlines
-# I am unable to make a case for this
-# without rerunning everything with $r as '\n'
-# I hope to fix this in the next commit
+printf '%s\n' "$out"
